theme: jekyll-theme-minimal
.
├── about.md    # => https://uwlib-cams.github.io/MARC2RDA/about.html
├── index.html    # => https://uwlib-cams.github.io/MARC2RDA/
└── contact.html  # => https://uwlib-cams.github.io/MARC2RDA/projectroster.html
